version: "3.8"
services:
  tempo:
    image: grafana/tempo:1.4.1
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./data/tempo:/tmp/tempo
    ports:
      - "14268:14268"  # jaeger ingest, Jaeger - Thrift HTTP
      - "14250:14250"  # Jaeger - GRPC
      - "3200:3200"    # Tempo
  grafana:
    image: grafana/grafana:8.5.0
    user: "0"
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    depends_on:
      - tempo
  otel-python-sample:
    build:
      context: .
      dockerfile: Dockerfile
    image: otel-python-sample:1.0
    environment:
      - TZ=Asia/Shanghai
    stdin_open: true
    tty: true
    depends_on:
      - grafana
    links:
      - "tempo:backend"