version: "3.8"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.34
    environment:
     - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250" # gRPC
      - "14268:14268" # Thrift
      - "14269:14269"
      - "9411:9411"
  otel-python-sample:
    build:
      context: .
      dockerfile: Dockerfile
    image: otel-python-sample:1.0
    environment:
      - TZ=Asia/Shanghai
    stdin_open: true
    tty: true
    links:
      - "jaeger:backend"