version: "3.8"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.34
    environment:
     - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250" # gRPC
      - "14268:14268" # Thrift
      - "14269:14269"
      - "9411:9411"
  otel-nginx-sample:
    image: nginx:1.22.0
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "otel-python-server-sample:python-end"
  otel-java-sample:
    build:
      context: .
      dockerfile: java/Dockerfile
    image: otel-java-sample:1.0
    ports:
      - "4081:4081"
    environment:
      - TZ=Asia/Shanghai
    links:
      - "jaeger:backend"
      - "otel-nginx-sample:nginx"
      - "otel-python-server-sample:python-end"
  otel-python-server-sample:
    build:
      context: .
      dockerfile: python/Dockerfile
    image: otel-python-server-sample:1.0
    environment:
      - TZ=Asia/Shanghai
    links:
      - "jaeger:backend"
